name: SSH Tunneling Client
version: 0.0.0
slug: ngrok
description: Establishes SSH tunnels for allow secure remote access.
init: false
url: https://github.com/dy1io/hassio-addons
stage: experimental
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: system
boot: auto 
options:
  log_level: info
  server: ""
  port: 22
  user: root
  force_new_sshkey: false
  tunnels:
    - type: remote
      tunnel: home:80:172.30.32.1:8123
schema:
  log_level: list(crit|warn|error|info|debug)
  server: str
  port: int
  user: str
  force_new_sshkey: bool
  tunnels:
    - tunnel: str?
