# Template for hassio-addons.

parameters:
  addon: ''
  arch: ''

jobs:

- job: '${{ parameters.addon }}'
  condition: eq(variables['Build.SourceBranchName'], 'master')
  pool:
    vmImage: 'ubuntu-latest'
  timeoutInMinutes: 360
  steps:
  - script: sudo docker login -u $(dockerUser) -p $(dockerToken)
    displayName: 'Docker hub login'
  - script: sudo docker pull homeassistant/amd64-builder:$(versionBuilder)
    displayName: 'Install Builder'
  - script: |
      sudo docker run --rm --privileged \
        -v ~/.docker:/root/.docker \
        -v /run/docker.sock:/run/docker.sock:rw -v $(pwd):/data:ro \
        homeassistant/amd64-builder:$(versionBuilder) \
        --addon ${{ parameters.arch }} -t /data \
        --docker-hub $(dockerRepo) --docker-hub-check
    displayName: 'Build ${{ parameters.addon }}'