name: CloudFlare Tunnels
arch:
  - amd64
  - aarch64
  - armhf
  - armv7
  - i386
version: dev
slug: cloudflared
description: Runs CloudFlare Tunnels
options:
  token: ""
schema:
  token: str
init: false
stage: experimental